import { ReactComponent as Search } from "./Search.svg";
import { ReactComponent as Down } from "./Down.svg";
import { ReactComponent as Right } from "./Right.svg";
import { ReactComponent as Left } from "./Left.svg";
import { ReactComponent as Male } from "./Male.svg";
import { ReactComponent as Female } from "./Female.svg";
import { ReactComponent as Table } from "./Table.svg";
import { ReactComponent as Shiny } from "./Shiny.svg";
import { ReactComponent as PokemonBall } from "./PokemonBall.svg";
export { Search, Down, Right, Left, Male, Female, Table, Shiny, PokemonBall };
